<a href="https://colab.research.google.com/github/trituenhantaoio/DeepLearning-Tutorial/blob/master/PyTorch_l%C3%A0_g%C3%AC%3F_trituenhantao_io.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


PyTorch là gì?
================

PyTorch là một gói tính toán khoa học trên Python phục vụ hai mục đích:

-  Thay thế NumPy để có thể tận dụng năng lực của GPU
-  Nền tảng nghiên cứu deep learning với tốc độ và tính linh hoạt tối đa

Khái niệm Tensor
--------

Tensor giống với kiểu ndarrays của NumPy nhưng có thể tận dụng được năng lực của GPU



In [ ]:
from __future__ import print_function
import torch

<div class="alert alert-info"><h4>Lưu ý</h4><p>Một ma trận được khai báo nhưng chưa được khởi tạo sẽ chứa các giá trị ngẫu nhiên ứng với vùng nhớ được cấp phát.</p></div>



Một ma trận 5x3 chưa được khởi tạo:



In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[3.2372e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 4.4842e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.1708e-19]])


Tạo và khởi tạo một ma trận ngẫu nhiên:



In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1361, 0.7655, 0.5600],
        [0.9114, 0.6982, 0.9220],
        [0.9907, 0.4667, 0.6908],
        [0.1704, 0.9689, 0.5001],
        [0.9206, 0.1919, 0.5747]])


Tạo một ma trận toàn số 0 với kiểu `long`:



In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Tạo một tensor trực tiếp từ dữ liệu:



In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Tạo một tensor từ một tensor có trước đó. Phương thức này sẽ sử dụng lại các thuộc tính của tensor đầu vào như kiểu dữ liệu nhưng không sao chép các giá trị chỉ định bởi người dùng.



In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.9655, -0.9916,  0.9088],
        [-1.0298, -1.4540,  0.1742],
        [-0.4296, -0.3974,  0.7019],
        [ 0.8502,  1.3975, -0.4322],
        [ 0.4934,  0.4787,  0.4768]])


Lấy thông tin về kích thước:



In [ ]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Lưu ý</h4><p>``torch.Size`` có dạng tuple nên nó hỗ trợ các toán tử trên tuple.</p></div>





Các phép tính
-------------
Có nhiều cú pháp để thực hiện các phép tính. Dưới đây là phép cộng

Phép cộng: cú pháp 1

In [ ]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.8471, -0.1484,  1.5518],
        [-0.6006, -0.7000,  1.0789],
        [-0.2447, -0.2121,  1.3138],
        [ 1.5165,  1.5652, -0.2420],
        [ 0.5450,  0.9149,  0.8941]])


Phép cộng: cú pháp 2

In [ ]:
print(torch.add(x, y))

tensor([[ 1.8471, -0.1484,  1.5518],
        [-0.6006, -0.7000,  1.0789],
        [-0.2447, -0.2121,  1.3138],
        [ 1.5165,  1.5652, -0.2420],
        [ 0.5450,  0.9149,  0.8941]])


Phép cộng: tensor kết quả được coi như một đối số



In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.8471, -0.1484,  1.5518],
        [-0.6006, -0.7000,  1.0789],
        [-0.2447, -0.2121,  1.3138],
        [ 1.5165,  1.5652, -0.2420],
        [ 0.5450,  0.9149,  0.8941]])


Phép cộng: dạng in-place



In [ ]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.8471, -0.1484,  1.5518],
        [-0.6006, -0.7000,  1.0789],
        [-0.2447, -0.2121,  1.3138],
        [ 1.5165,  1.5652, -0.2420],
        [ 0.5450,  0.9149,  0.8941]])


<h4>Lưu ý</h4>

Các toán tử dạng in-place trên tensor đều kết thúc bằng ký tự ``_``.
    Ví dụ: `x.copy_(y)`, `x.t_()`, sẽ làm thay đổi giá trị của ``x``.

Ta có thể sử dụng cách đánh chỉ số giống NumPy trên PyTorch.



In [ ]:
print(x[:, 1])

tensor([-0.9916, -1.4540, -0.3974,  1.3975,  0.4787])


In [ ]:
print(x)

tensor([[ 0.9655, -0.9916,  0.9088],
        [-1.0298, -1.4540,  0.1742],
        [-0.4296, -0.3974,  0.7019],
        [ 0.8502,  1.3975, -0.4322],
        [ 0.4934,  0.4787,  0.4768]])


Định dạng lại tensor: Nếu muốn định hình (định dạng) lại một tensor, bạn có thể sử dụng ``torch.view``:



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Với tensor có 1 phần tử, ta có thể sử dụng ``.item()`` để lấy ra giá trị số của nó



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3834])
0.383449524641037


**Đọc thêm:**


  Hơn 100 phép toán trên Tensor bao gồm chuyển vị, đánh chỉ mục, slicing, phép toán trên ma trận, đại số tuyến tính, các số ngẫu nhiên v..v.. được mô tả tại [đây](https://pytorch.org/docs/torch).

Chuyển đổi với NumPy
------------

Việc chuyển đổi Tensor của Torch sang Numpy và ngược lại được thực hiện rất đơn giản.

Hai kiểu dữ liệu này có chung bộ nhớ được cấp phát (với Tensor nằm trên CPU).

Chuyển đổi Torch Tensor thành NumPy Array




In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


Xem giá trị mảng bị thay đổi như thế nào

In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Chuyển đổi NumPy Array sang Torch Tensor và xem Tensor bị thay đổi như thế nào khi thay đổi giá trị của mảng



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Ngoại trừ CharTensor, mọi kiểu Tensor của Torch đều có thể chuyển đổi qua lại với NumPy

CUDA Tensor
------------

Tensor có thể chuyển sang mọi thiết bị với phương thức ``.to``



In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.3834], device='cuda:0')
tensor([1.3834], dtype=torch.float64)
